.TH sdagent-monitor 8 "18 Mar 2014" "sdagent-monitor" "Support Utilities Manual"
.SH NAME
sdagent-monitor - SCA Agent Monitor Tool
.SH SYNOPSIS
sdagent-monitor
.SH DESCRIPTION
Monitors the agent server CPU utilization
.SH OPTIONS
.TP
None
.SH AUTHOR
Jason Record <jrecord@suse.com>
.SH COPYRIGHT
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; version 2 of the License.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with this program; if not, see <http://www.gnu.org/licenses/>.
.SH SEE ALSO
.BR sdagent-monitor.conf (5)

