.TH sdagent-health.conf 5 "01 Mar 2013" "sdagent-patterns.conf" "Supportconfig Diagnostic Manual"
.SH NAME
sdagent-health.conf - Supportconfig Diagnostic Agent Health Tool specific configuration file
.SH DESCRIPTION
The \fBsdagent-health\fR script uses \fBsdagent.conf\fR for default global variable values. If \fBsdagent-health.conf\fR is present, it will override any global variables that were set in \fBsdagent.conf\fR.
.SH GLOBAL VARIABLES
Same as \fBsdagent.conf\fR(5).
.SH AUTHOR
Jason Record <jrecord@suse.com>
.SH COPYRIGHT
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; version 2 of the License.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.SH SEE ALSO
.BR sdagent.conf (5)
.BR sdagent-health (1)

